### ISSUE TITLE
docker compose build fails due to pip error

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/OperationHub#33]
The build fails with the following error.

```
 => ERROR [jupyterhub builder 6/9] RUN python3 -m pip wheel --wheel-dir wheelhouse --constraint requirements     git  3.0s
------
 > [jupyterhub builder 6/9] RUN python3 -m pip wheel --wheel-dir wheelhouse --constraint requirements     git+https://githu
b.com/NII-cloud-operation/Jupyter-LC_nblineage.git:
0.952 Collecting git+https://github.com/NII-cloud-operation/Jupyter-LC_nblineage.git
0.953   Cloning https://github.com/NII-cloud-operation/Jupyter-LC_nblineage.git to ./pip-req-build-6ps8384y
0.958   Running command git clone --filter=blob:none --quiet https://github.com/NII-cloud-operation/Jupyter-LC_nblineage.gi
t /tmp/pip-req-build-6ps8384y
2.161   Resolved https://github.com/NII-cloud-operation/Jupyter-LC_nblineage.git to commit c310decc8ae6aa597ff6129aca595201
2d7e9896
2.167   Preparing metadata (setup.py): started
2.563   Preparing metadata (setup.py): finished with status 'error'
2.603   error: subprocess-exited-with-error
2.603
2.603   × python setup.py egg_info did not run successfully.
2.603   │ exit code: 1
2.603   ╰─> [41 lines of output]
2.603       running egg_info
2.603       creating /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info
2.603       writing /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/PKG-INFO
2.603       writing dependency_links to /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/dependency_links.txt
2.603       writing entry points to /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/entry_points.txt
2.603       writing requirements to /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/requires.txt
2.603       writing top-level names to /tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/top_level.txt
2.603       writing manifest file '/tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/SOURCES.txt'
2.603       reading manifest file '/tmp/pip-pip-egg-info-qo9y28du/lc_nblineage.egg-info/SOURCES.txt'
2.603       reading manifest template 'MANIFEST.in'
2.603       adding license file 'LICENSE.txt'
2.603       Traceback (most recent call last):
2.603         File "<string>", line 2, in <module>
2.603         File "<pip-setuptools-caller>", line 34, in <module>
2.603         File "/tmp/pip-req-build-6ps8384y/setup.py", line 32, in <module>
2.603           setup(**setup_args)
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 111, in setup
2.603           return distutils.core.setup(**attrs)
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 184, in setup
2.603           return run_commands(dist)
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
2.603           dist.run_commands()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 964, in run_commands
2.603           self.run_command(cmd)
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 948, in run_command
2.603           super().run_command(command)
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 983, in run_command
2.603           cmd_obj.run()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 311, in run
2.603           self.find_sources()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 319, in find_sources
2.603           mm.run()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 545, in run
2.603           self.prune_file_list()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 611, in prune_file_list
2.603           base_dir = self.distribution.get_fullname()
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_core_metadata.py", line 267, in get_fullname
2.603           return _distribution_fullname(self.get_name(), self.get_version())
2.603         File "/usr/local/lib/python3.8/dist-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
2.603           canonicalize_version(version, strip_trailing_zero=False),
2.603       TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
2.603       [end of output]
2.603
2.603   note: This error originates from a subprocess, and is likely not a problem with pip.
2.620 error: metadata-generation-failed
2.620
2.620 × Encountered error while generating package metadata.
2.620 ╰─> See above for output.
2.620
2.620 note: This is an issue with the package mentioned above, not pip.
2.620 hint: See above for details.
```

**Comment by yacchin1205** [comment]
This issue is supposed to be reported as https://github.com/pypa/setuptools/issues/4483 .

It would seem that updating the packaging would solve the problem, but there is currently no reason to upgrade the setuptools anyway...
